image: node:18

stages:
  - build
  - android

variables:
  ANDROID_HOME: "/opt/android-sdk"
  ANDROID_SDK_ROOT: "/opt/android-sdk"

before_script:
  - apt-get update -qq && apt-get install -y -qq git curl unzip openjdk-17-jdk
  - export JAVA_HOME=/usr/lib/jvm/java-17-openjdk-amd64
  - export PATH=$PATH:$JAVA_HOME/bin
  - curl -sL https://dl.google.com/android/repository/commandlinetools-linux-11076708_latest.zip -o cmdline-tools.zip
  - unzip -q cmdline-tools.zip
  - mkdir -p $ANDROID_HOME/cmdline-tools
  - mv cmdline-tools $ANDROID_HOME/cmdline-tools/latest
  - export PATH=$PATH:$ANDROID_HOME/cmdline-tools/latest/bin
  - yes | sdkmanager --licenses
  - sdkmanager "platform-tools" "platforms;android-34" "build-tools;34.0.0"

build_web:
  stage: build
  script:
    - npm install
    - npm run build
  artifacts:
    paths:
      - dist/
    expire_in: 1 hour

build_android:
  stage: android
  dependencies:
    - build_web
  script:
    - npx cap sync
    - cd android
    - ./gradlew assembleDebug
  artifacts:
    paths:
      - android/app/build/outputs/apk/debug/app-debug.apk
    expire_in: 1 week
