// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rpihyvkoblelvekuqeee.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJwaWh5dmtvYmxlbHZla3VxZWVlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjA5Nzg1ODEsImV4cCI6MjA3NjU1NDU4MX0.0VtHfDFEHsUbFcJasqpgjQCPtgWtBNo-3XfSAkUTwh4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});